name := "Mindscape Mark II Framework"
organization := "co.mscp"

libraryDependencies += "com.typesafe.play" %% "play-json" % "2.7.0"
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.2.3"
libraryDependencies += "org.apache.httpcomponents" % "httpclient" % "4.5.5"
libraryDependencies += "com.fasterxml.jackson.core" % "jackson-core" % "2.9.5"
libraryDependencies += "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.5"
libraryDependencies += "com.fasterxml.jackson.core" % "jackson-annotations" % "2.9.5"
libraryDependencies += "com.fasterxml.jackson.module" % "jackson-module-scala_2.12" % "2.9.9"